- name: Create the wg network
  community.general.docker_network:
    name: wg_network
    ipam_config:
      - subnet: "{{ ip_start }}2.0/24"
        gateway: "{{ ip_start }}2.1"
        iprange: "{{ ip_start }}2.0/24"
